### PR TITLE
Made all private properties protected

### PR DESCRIPTION
**Pull request by upchuk**
I made all the private properties protected so that when extending the class, those values can be accessed.

### CODE REVIEW

**Comment by sgrodzicki** [comment]
Making them `protected` makes them also open for modification. IMO they should be exposed with `protected` getters.

P.S. Don't you want to add those 4 methods you mentioned in #2?

**Comment by upchuk** [comment]
Hey @sgrodzicki 

Unfortunately don't have the time to create the methods. However, extension should be possible I think, otherwise there is very limited scope for usage. 

Regarding your point, making them protected makes them open only for extending classes which will supposedly only be the ones that want to add new methods to the existing ones. In which case, I don't think this is a problem. They will be used just as the `Client` class itself uses it. You disagree? :)

**Comment by sgrodzicki** [comment]
The username, password and token are passed to the constructor and shouln't be modified later on. Making them `protected` breaks that assumption. Instead a getter should be used:

``` php
protected function getUsername()
{
    return $this->username;
}
```

**Comment by upchuk** [comment]
Alright, there you go, protected methods :) Something went wrong with my text editor so I had to fix that...

D

**Pull request merged**
